/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import classConectar.conectar;
import com.sun.awt.AWTUtilities;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class ConsultasProductos extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form ConsultasProductos
     */
    public ConsultasProductos() {
           initComponents();
           AWTUtilities.setWindowOpaque(this,false);
          setLocationRelativeTo(ventanaadmin.escritorio);
          
    }
    

       void cargar(String valor) {
        try{
            String [] titulos={"Codigo","Descripcion","Precio","Stock","tipo producto"};
            String [] registros= new String[6];
            model=new DefaultTableModel(null,titulos);
            
            String cons="select * from producto,tipoproducto WHERE producto.id_tipo= tipoproducto.id_tipo && CONCAT (descripcion,'',precio) LIKE '%"+valor+"%'";
            Statement st= cn.createStatement();
            ResultSet rs = st.executeQuery(cons);
            while(rs.next()){
                registros[0]=rs.getString("cod_pro");
                registros[1]=rs.getString("descripcion");
                registros[2]=rs.getString("precio");
                registros[3]=rs.getString("Stock");
                 registros[4]=rs.getString("descrip");
             
                
                model.addRow(registros);      
                }
            tbproductos.setModel(model);
            tbproductos.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbproductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbproductos.getColumnModel().getColumn(2).setPreferredWidth(80);
             tbproductos.getColumnModel().getColumn(3).setPreferredWidth(50);
              tbproductos.getColumnModel().getColumn(4).setPreferredWidth(140);
            }catch(Exception e){
                System.out.println(e.getMessage());
                 }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        rbtntodo = new javax.swing.JRadioButton();
        rbtndes = new javax.swing.JRadioButton();
        txtdes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 380));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 153, 0));
        jButton3.setText("sALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 20));

        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbproductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 650, 390));

        rbtntodo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtntodo.setText("tODOS lOS pRODUCTOS");
        rbtntodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtntodoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtntodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        rbtndes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rbtndes.setSelected(true);
        rbtndes.setText("bUSCAR pRODUCTO pOR nOMBRE");
        rbtndes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtndesMouseClicked(evt);
            }
        });
        jPanel1.add(rbtndes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtdes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdesKeyReleased(evt);
            }
        });
        jPanel1.add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtntodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtntodoActionPerformed
        // TODO add your handling code here:
        if(rbtntodo.isSelected()==true)
        {
            txtdes.setText("");
            txtdes.setEnabled(false);
           cargar("");
        }

    }//GEN-LAST:event_rbtntodoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rbtndesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtndesMouseClicked
         if(rbtndes.isSelected()==true)
        {
            txtdes.setEnabled(true);
            txtdes.requestFocus();
        }
    }//GEN-LAST:event_rbtndesMouseClicked

    private void txtdesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesKeyReleased
       cargar(txtdes.getText());
    }//GEN-LAST:event_txtdesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtndes;
    private javax.swing.JRadioButton rbtntodo;
    private javax.swing.JTable tbproductos;
    private javax.swing.JTextField txtdes;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
}
