/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import classConectar.conectar;
import com.sun.awt.AWTUtilities;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class ConsultasVentas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasVentas
     */
    public ConsultasVentas() {
        initComponents();
        AWTUtilities.setWindowOpaque(this,false);
        setResizable(false); 
        setLocationRelativeTo(ventanaadmin.escritorio); 
         cargartodasBoletas();
        jDateChooser1.setEnabled(false);
    }
    
       void cargartodasBoletas()
    {
        DefaultTableModel tabla= new DefaultTableModel();
        String []titulos={"Numero","Codigo de cliente","Total a pagar","Fecha"};
        tabla.setColumnIdentifiers(titulos);
        this.tbboletas.setModel(tabla);
        String consulta= "SELECT * FROM venta";
        String []Datos= new String [4];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString("num_bol");
                Datos[1]=rs.getString("cod_cli");
                Datos[2]=rs.getString("pre_tot");
                Datos[3]=rs.getString("fecha");
                
                
                tabla.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
       void Buscar(){
        

        String consulta="";
      
        if(rdbbnfecha.isSelected()==true)
        {
            Date fecha=jDateChooser1.getDate();
            SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
            String fec=""+formatofecha.format(fecha);
            consulta= "SELECT * FROM venta WHERE fecha='"+fec+"'";
        }
        if(rdbntodos.isSelected()==true)
        {
            consulta= "SELECT * FROM venta ";
        }
        DefaultTableModel tabla= new DefaultTableModel();
        String []titulos={"Numero","Codigo de cliente","Total a pagar","Fecha"};
        tabla.setColumnIdentifiers(titulos);
        tbboletas.setModel(tabla);

        String []Datos= new String [4];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString("num_bol");
                Datos[1]=rs.getString("cod_cli");
                Datos[2]=rs.getString("pre_tot");
                Datos[3]=rs.getString("fecha");

                tabla.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnbuscador = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        rdbbnfecha = new javax.swing.JRadioButton();
        rdbntodos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbboletas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbuscador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnbuscador.setText("BUSCAR");
        btnbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscadorActionPerformed(evt);
            }
        });
        btnbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbuscadorKeyPressed(evt);
            }
        });
        jPanel1.add(btnbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 80));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, 30));

        rdbbnfecha.setBackground(new java.awt.Color(255, 255, 255));
        rdbbnfecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbbnfecha.setText("Mostrar por Fecha");
        rdbbnfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbbnfechaMouseClicked(evt);
            }
        });
        rdbbnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnfechaActionPerformed(evt);
            }
        });
        jPanel1.add(rdbbnfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 40));

        rdbntodos.setBackground(new java.awt.Color(255, 255, 255));
        rdbntodos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbntodos.setText("Mostrar todas:");
        rdbntodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbntodosActionPerformed(evt);
            }
        });
        jPanel1.add(rdbntodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        tbboletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbboletas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 650, 410));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("sALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbbnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnfechaActionPerformed
        // TODO add your handling code here:
        if(rdbbnfecha.isSelected()==true)
        {
            jDateChooser1.setEnabled(true);
          

        }
    }//GEN-LAST:event_rdbbnfechaActionPerformed

    private void rdbntodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbntodosActionPerformed
        // TODO add your handling code here:
        if(rdbntodos.isSelected()==true)
        {
            jDateChooser1.setEnabled(false);
            jDateChooser1.setDate(null);
            
            cargartodasBoletas();
        }

    }//GEN-LAST:event_rdbntodosActionPerformed

    private void btnbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscadorActionPerformed
     Buscar();

       

    }//GEN-LAST:event_btnbuscadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbbnfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbbnfechaMouseClicked
       jDateChooser1.requestFocusInWindow();
    }//GEN-LAST:event_rdbbnfechaMouseClicked

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
 btnbuscador.requestFocusInWindow();
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void btnbuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbuscadorKeyPressed
        Buscar();
    }//GEN-LAST:event_btnbuscadorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscador;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbbnfecha;
    private javax.swing.JRadioButton rdbntodos;
    public static javax.swing.JTable tbboletas;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
}
