/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import classConectar.conectar;
import com.sun.awt.AWTUtilities;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class IngresoSistema extends javax.swing.JFrame {

    /**
     * Creates new form IngresoSistema
     */
    int x,y;
    public IngresoSistema() {
        initComponents();
        setSize(655,559); 
        AWTUtilities.setWindowOpaque(this,false);
        setLocationRelativeTo(null);
       
    }
    
     void acceder(String usuario, String pass)
    {
       String cap="";
       String sql="SELECT * FROM usuario WHERE nick='"+usuario+"' and password='"+pass+"'";
       
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                cap=rs.getString("id_puesto");
            }
                    if(cap.equals("1"))
                    {
                          this.setVisible(false);
                            JOptionPane.showMessageDialog(null, "Bienvenido Administrador");
                            ventanaadmin ingreso = new ventanaadmin();
                            ingreso.setVisible(true);
                            ingreso.pack();
                             ventanaadmin.lblusu.setText(usuario);
                            


                    }
                            if(cap.equals("2"))
                            {
                            this.setVisible(false);
                                    JOptionPane.showMessageDialog(null, "Bienvenido Empleado ");
                                     ventanacliente ingresos = new ventanacliente();
                                     ingresos.lblconectado.setText(txtusuario.getText());
                                     ingresos.setVisible(true);
                                     ingresos.pack();
                                     
                            }
                        
                            
                            
                                    if((!cap.equals("1"))&& (!cap.equals("2")) )
                                    {
                                        JOptionPane.showMessageDialog(this, "Verifique su nick y password ", null,JOptionPane.ERROR_MESSAGE);
                                        txtusuario.setText("");
                                        txtcontra.setText("");
                                        txtusuario.requestFocusInWindow();
                                    }
        } catch (SQLException ex) {
            Logger.getLogger(IngresoSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JPasswordField();
        btnentrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbbarra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/marcas2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 290, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(204, 204, 255));
        txtusuario.setText("Ingrese Usuario");
        txtusuario.setToolTipText("");
        txtusuario.setBorder(null);
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusuarioMouseClicked(evt);
            }
        });
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 230, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("uSER");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("pASSWORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        txtcontra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcontra.setForeground(new java.awt.Color(204, 204, 255));
        txtcontra.setText("           ");
        txtcontra.setBorder(null);
        txtcontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcontraMouseClicked(evt);
            }
        });
        txtcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraActionPerformed(evt);
            }
        });
        jPanel2.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 230, 40));

        btnentrar.setBackground(new java.awt.Color(0, 0, 0));
        btnentrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(204, 153, 0));
        btnentrar.setText("eNTER");
        btnentrar.setBorder(null);
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        btnentrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnentrarKeyPressed(evt);
            }
        });
        jPanel2.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("sING iN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 170, 110));

        lbbarra.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lbbarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbbarraMouseDragged(evt);
            }
        });
        lbbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbbarraMousePressed(evt);
            }
        });
        jPanel2.add(lbbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 280, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8_Multiply_32px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 390, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        String nulo="";
        if(txtusuario.getText().equals(nulo)){
            JOptionPane.showMessageDialog(null, "Campo usuario es necesario");
        }else {
            txtcontra.setText("");
            txtcontra.requestFocusInWindow();
        }

    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraActionPerformed
        String nulo="";
        if(txtcontra.getText().equals(nulo)){
            JOptionPane.showMessageDialog(null, "Campo password es necesario");
        }else {
            btnentrar.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtcontraActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        String usu=txtusuario.getText();
        String pas=new String(txtcontra.getPassword());
        acceder(usu, pas);
    }//GEN-LAST:event_btnentrarActionPerformed

    private void btnentrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnentrarKeyPressed
        String usu=txtusuario.getText();
        String pas=new String(txtcontra.getPassword());
        acceder(usu, pas);
    }//GEN-LAST:event_btnentrarKeyPressed

    private void lbbarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbarraMousePressed
       x = evt.getX();
       y = evt.getY();
    }//GEN-LAST:event_lbbarraMousePressed

    private void lbbarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY()- y);
    }//GEN-LAST:event_lbbarraMouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
              int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de salir  ?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 1){
             this.setVisible(true);
        }else{
         this.dispose();
         System.exit(0);
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMouseClicked
     txtusuario.setText("");
    }//GEN-LAST:event_txtusuarioMouseClicked

    private void txtcontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraMouseClicked
       txtcontra.setText("");
    }//GEN-LAST:event_txtcontraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbbarra;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
}
