/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import classConectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class usuarios extends javax.swing.JFrame {
DefaultTableModel modelo;
    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
        setLocationRelativeTo(ventanaadmin.escritorio);
        mostrarusuarios();
        Generarnumeracion();
        mostrartipousuario();
    }

        void Generarnumeracion()
    {
     String SQL="select max(idusuario) from usuario";
        
          int c=0;
          int b=0;
        try {
           Statement st = cn.createStatement();
           ResultSet rs=st.executeQuery(SQL);
            while(rs.next())
            {              
                 c=rs.getInt(1);
            }
            
           
            if(c==0){
                txtid.setText("1");
            }
            else
            {
                
                txtid.setText(""+(c+1));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
        
          void mostrartipousuario(){
       String sql="Select * from id_puesto";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                cbotipo.addItem(rs.getString("tipo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresoProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
        
        
        void mostrarusuarios(){
   String [] titulos= {"id","Usuario","Tipo de Usuario"};
   modelo=new  DefaultTableModel(null,titulos);   
   String datos []= new String[5];
   String sql="SELECT * FROM  usuario"; 
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                datos[0]=rs.getString("idusuario");
                datos[1]=rs.getString("nick");
                datos[2]= rs.getString("id_puesto");
                modelo.addRow(datos);
            }
            tbusuario.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
  
  
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnick = new javax.swing.JTextField();
        cbotipo = new javax.swing.JComboBox();
        txtpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuario = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tipo Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        txtid.setEditable(false);
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, 40));
        jPanel1.add(txtnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, 40));

        cbotipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jPanel1.add(cbotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 190, 40));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 370, 270));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("sALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 80, 20));

        tbusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbusuario);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 690, 280));

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, 60));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 120, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        JPasswordField pwd = new JPasswordField(12);
        int fila= tbusuario.getSelectedRow();
        if(fila<0)
        {
            JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
        }
        else
        {
            idfila= tbusuario.getValueAt(fila, 0).toString();
            String contra = JOptionPane.showInputDialog(null, "Escribe tu contraseña de usuario administrador"+new String(pwd.getPassword()));
            String passdb="";
        

        String nomusuario= ventanaadmin.lblusu.getText();
        System.out.print(nomusuario);
        String sql="SELECT * FROM usuario WHERE nick='"+nomusuario+"'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                passdb=rs.getString("password");
                
            }
            System.out.println(passdb);
            
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(passdb.equals(contra))
        {
                
            
            String eli="DELETE FROM usuario WHERE idusuario = '"+idfila+"'";
            PreparedStatement pst;
            try {
                pst = cn.prepareStatement(eli);
                int m=pst.executeUpdate();
                if(m>0){
                    JOptionPane.showMessageDialog(this, "elimino regisro");
                    mostrarusuarios();
                    

                }
            else
                {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Verificacion ***", JOptionPane.WARNING_MESSAGE);
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                    mostrarusuarios();
                }

            } catch (SQLException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
         String nulo="";
        if(txtnick.getText().equals(nulo)){
            JOptionPane.showMessageDialog(null, "Campo Nick es necesario");
        }else if (txtpass.getText().equals(nulo)){
           JOptionPane.showMessageDialog(null, "Campo Password es necesario");
        }else if (cbotipo.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(null, "Campo tipo es necesario");
        }else {
        
        
         btnregistrar.requestFocusInWindow();
        
        
        String ins="INSERT INTO usuario (nick, password, id_puesto) VALUES(?,?,?)";
        try {
            PreparedStatement pst = cn.prepareStatement(ins);
            pst.setString(1, txtnick.getText());
            pst.setString(2,new String(txtpass.getPassword()));
             pst.setInt(3, cbotipo.getSelectedIndex());
            
            int n= pst.executeUpdate();
            if(n>0)
            {
                JOptionPane.showMessageDialog(this, "Se guardaron los datos");
                mostrarusuarios();
                txtnick.setText(null);
                txtpass.setText(null);
                cbotipo.setSelectedIndex(0);
                Generarnumeracion();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error");
            }

        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        }  
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox cbotipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbusuario;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnick;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
 conectar cc = new conectar();
    Connection cn = cc.conexion();
      String idfila="";
}
