/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

//import static Formulario.Venta.fechaact;
import classConectar.conectar;
import java.util.Calendar;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import AppPackage.AnimationClass;
import javax.swing.JLabel;

/**
 *
 * @author jesus
 */
public class ventanaadmin extends javax.swing.JFrame {
int x,y;
    /**
     * Creates new form ventanaadmin
     */
    public ventanaadmin() {
        initComponents();
        setLocationRelativeTo(null); 
        txtfecha.setText(fechaact());
        hora();
       
    }
     void hora(){
         Calendar cal = Calendar.getInstance(); 
         String hora;
         
         hora=cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
         
         this.labhora.setText(hora);
    }
     public static String fechaact(){
    java.util.Date fecha= new java.util.Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
    return formatofecha.format(fecha);
    }  
     
     
     void Menu(Object campo ){
     AnimationClass menuflotante = new AnimationClass();
     menuflotante.jLabelXRight(-35, 20, 10, 5, (JLabel) campo);
     AnimationClass menuflotantee = new AnimationClass();
     menuflotantee.jLabelXLeft(20, -35, 10, 5, (JLabel) campo);
     
     }
     
     void OcultaFormularios(){
         
    IngresoCliente cli= new IngresoCliente();
    cli.dispose();
    IngresoProductos ip= new IngresoProductos();
    ip.setVisible(false);
     usuarios usu= new usuarios();
     usu.setVisible(false);
     ConsultasVentas nueva= new  ConsultasVentas();
     nueva.setVisible(false);
      ConsultasClientes clientes= new ConsultasClientes();
      clientes.setVisible(false);
      ConsultasProductos productos= new ConsultasProductos();
      productos.setVisible(false);
      Venta venta = new Venta();
      venta.setVisible(false);  
     }
   
 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        lbbarra = new javax.swing.JLabel();
        jLtituloprincipal = new javax.swing.JLabel();
        jLtitulocatalogo = new javax.swing.JLabel();
        jLcatalogo_clientes = new javax.swing.JLabel();
        jLcatalogo_productos = new javax.swing.JLabel();
        jLprose_venta = new javax.swing.JLabel();
        jLtituloventa = new javax.swing.JLabel();
        jLtituloconsulta = new javax.swing.JLabel();
        jLconsulta_venta = new javax.swing.JLabel();
        jLconsulta_clientes = new javax.swing.JLabel();
        jLconsulta_productos = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        jpcatalogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpproceso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPmenuprincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpcerrarsesion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpconsulta = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        labhora = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        btmenuflot = new javax.swing.JLabel();
        jlconfig = new javax.swing.JLabel();
        jlclave = new javax.swing.JLabel();
        jlcerrarsistema = new javax.swing.JLabel();
        jpreporte = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 3));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escritorio.setMinimumSize(new java.awt.Dimension(740, 750));
        escritorio.setPreferredSize(new java.awt.Dimension(740, 750));
        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbbarra.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lbbarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbbarraMouseDragged(evt);
            }
        });
        lbbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbbarraMousePressed(evt);
            }
        });
        escritorio.add(lbbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        jLtituloprincipal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLtituloprincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloprincipal.setText("_bIENVENIDO_");
        escritorio.add(jLtituloprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 480, 70));

        jLtitulocatalogo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLtitulocatalogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulocatalogo.setText("mENU_cATALOGO");
        escritorio.add(jLtitulocatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 480, 70));

        jLcatalogo_clientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLcatalogo_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcatalogo_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/001-tecnologia.png"))); // NOI18N
        jLcatalogo_clientes.setText("  cLIENTES");
        jLcatalogo_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLcatalogo_clientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLcatalogo_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcatalogo_clientesMouseClicked(evt);
            }
        });
        escritorio.add(jLcatalogo_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 300, 140));

        jLcatalogo_productos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLcatalogo_productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcatalogo_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/003-comida.png"))); // NOI18N
        jLcatalogo_productos.setText("pRODUCTOS ");
        jLcatalogo_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLcatalogo_productos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLcatalogo_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcatalogo_productosMouseClicked(evt);
            }
        });
        escritorio.add(jLcatalogo_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 300, 140));

        jLprose_venta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLprose_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLprose_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/008-bolsa.png"))); // NOI18N
        jLprose_venta.setText("vENTA");
        jLprose_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLprose_venta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLprose_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLprose_ventaMouseClicked(evt);
            }
        });
        escritorio.add(jLprose_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 300, 140));

        jLtituloventa.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLtituloventa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloventa.setText("mENU_pROCESO");
        escritorio.add(jLtituloventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 480, 70));

        jLtituloconsulta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLtituloconsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloconsulta.setText("mENU_cONSULTA");
        escritorio.add(jLtituloconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 480, 70));

        jLconsulta_venta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLconsulta_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLconsulta_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/004-linea-1.png"))); // NOI18N
        jLconsulta_venta.setText("vENTA");
        jLconsulta_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLconsulta_venta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLconsulta_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLconsulta_ventaMouseClicked(evt);
            }
        });
        escritorio.add(jLconsulta_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 300, 140));

        jLconsulta_clientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLconsulta_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLconsulta_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/002-perfil.png"))); // NOI18N
        jLconsulta_clientes.setText("  cLIENTES");
        jLconsulta_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLconsulta_clientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLconsulta_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLconsulta_clientesMouseClicked(evt);
            }
        });
        escritorio.add(jLconsulta_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 300, 140));

        jLconsulta_productos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLconsulta_productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLconsulta_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/006-imprimir.png"))); // NOI18N
        jLconsulta_productos.setText("pRODUCTOS ");
        jLconsulta_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLconsulta_productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLconsulta_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLconsulta_productosMouseClicked(evt);
            }
        });
        escritorio.add(jLconsulta_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 300, 140));

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 740, 710));

        sidepanel.setBackground(new java.awt.Color(255, 255, 255));
        sidepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 3));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpcatalogo.setBackground(new java.awt.Color(255, 204, 153));
        jpcatalogo.setForeground(new java.awt.Color(0, 51, 102));
        jpcatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpcatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpcatalogoMouseClicked(evt);
            }
        });
        jpcatalogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/004-interfaz-1.png"))); // NOI18N
        jpcatalogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("cATALOGO");
        jpcatalogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jpcatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 300, 50));

        jpproceso.setBackground(new java.awt.Color(255, 204, 153));
        jpproceso.setForeground(new java.awt.Color(0, 51, 102));
        jpproceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpproceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpprocesoMouseClicked(evt);
            }
        });
        jpproceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/008-dibujar-1.png"))); // NOI18N
        jpproceso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("pROCESOS");
        jpproceso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jpproceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 50));

        jPmenuprincipal.setBackground(new java.awt.Color(255, 204, 153));
        jPmenuprincipal.setForeground(new java.awt.Color(0, 51, 102));
        jPmenuprincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPmenuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPmenuprincipalMouseClicked(evt);
            }
        });
        jPmenuprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/010-construccion-1.png"))); // NOI18N
        jPmenuprincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("iNICIO");
        jPmenuprincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jPmenuprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 300, 50));

        jpcerrarsesion.setBackground(new java.awt.Color(255, 204, 153));
        jpcerrarsesion.setForeground(new java.awt.Color(0, 51, 102));
        jpcerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpcerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpcerrarsesionMouseClicked(evt);
            }
        });
        jpcerrarsesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jpcerrarsesion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("cERRA sESION");
        jpcerrarsesion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jpcerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 50));

        jpconsulta.setBackground(new java.awt.Color(255, 204, 153));
        jpconsulta.setForeground(new java.awt.Color(0, 51, 102));
        jpconsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpconsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpconsultaMouseClicked(evt);
            }
        });
        jpconsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/003-busqueda-1.png"))); // NOI18N
        jpconsulta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("cONSULTAS");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpconsulta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jpconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 300, 50));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/001-social-4.png"))); // NOI18N
        sidepanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 90));

        lblusu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidepanel.add(lblusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 50));

        labhora.setBackground(new java.awt.Color(0, 0, 204));
        labhora.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labhora.setText("hora");
        sidepanel.add(labhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 200, 30));

        txtfecha.setBackground(new java.awt.Color(0, 0, 204));
        txtfecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtfecha.setText("fecha");
        sidepanel.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 200, 50));

        btmenuflot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmenuflot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8_Menu_32px.png"))); // NOI18N
        btmenuflot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmenuflot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmenuflotMouseClicked(evt);
            }
        });
        sidepanel.add(btmenuflot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jlconfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/016-rueda-dentada.png"))); // NOI18N
        jlconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlconfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlconfigMouseClicked(evt);
            }
        });
        sidepanel.add(jlconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 100, 30, 30));

        jlclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlclave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/017-clave.png"))); // NOI18N
        sidepanel.add(jlclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 60, 30, 30));

        jlcerrarsistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarsistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons8_Multiply_32px.png"))); // NOI18N
        jlcerrarsistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlcerrarsistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarsistemaMouseClicked(evt);
            }
        });
        sidepanel.add(jlcerrarsistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 140, 30, 30));

        jpreporte.setBackground(new java.awt.Color(255, 204, 153));
        jpreporte.setForeground(new java.awt.Color(0, 51, 102));
        jpreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpreporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/001-negocios-1.png"))); // NOI18N
        jpreporte.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("rEPORTES");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpreporte.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        sidepanel.add(jpreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 300, 50));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 710));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255), 2));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Catalogo");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Clientes");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem10.setText("Venta");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Productos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem11.setText("Ventas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jMenuItem6.setText("Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem12.setText("Productos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem14.setText("Ventas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Administrador");

        jMenuItem15.setText("Nuevo Usuario");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿sEGURO DE CERRAR SESION?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 1){
             this.setVisible(true);
        }else{
         
          IngresoSistema principal= new IngresoSistema();
            principal.setVisible(true);
             this.setVisible(false);
            
        }      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de salir  ?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 1){
             this.setVisible(true);
        }else{
         this.dispose();
         System.exit(0);
        }
        
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        IngresoProductos ip= new IngresoProductos();
        this.toFront();
        ip.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        IngresoCliente cli= new IngresoCliente();
        
          this.toFront();
          cli.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
     Venta venta = new Venta();
   
    venta.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ConsultasClientes clientes= new ConsultasClientes();
       
        clientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ConsultasProductos productos= new ConsultasProductos();
       
        productos.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        ConsultasVentas nueva= new  ConsultasVentas();
         this.toFront();
       nueva.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed
conectar cc = new conectar();
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
conectar cc = new conectar();
        try {
             //conectar cc = new conectar();

            JasperReport reportes=JasperCompileManager.compileReport("reportesClientes.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            JasperViewer.viewReport(print);

        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        try {
            conectar cc= new conectar();

            JasperReport reportes=JasperCompileManager.compileReport("reportesProductos.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            JasperViewer.viewReport(print);

        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        try {
            conectar cc= new conectar();

            JasperReport reportes=JasperCompileManager.compileReport("reportesVentas.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            JasperViewer.viewReport(print);

        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       usuarios usu= new usuarios();
       this.toFront();
       usu.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void btmenuflotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmenuflotMouseClicked
     
     Menu(jlconfig); 
     Menu(jlclave);
     Menu(jlcerrarsistema);
    
    }//GEN-LAST:event_btmenuflotMouseClicked

    private void jpcatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpcatalogoMouseClicked
    AnimationClass muestracatalogo = new AnimationClass();
     muestracatalogo.jLabelXLeft(750, 200, 3, 5, jLcatalogo_clientes);
    
    muestracatalogo.jLabelXLeft(750, 200, 3, 5, jLcatalogo_productos);
    
     muestracatalogo.jLabelXLeft(750, 120, 3, 5, jLtitulocatalogo);
       
      AnimationClass ocultaBienvenida = new AnimationClass();
       ocultaBienvenida.jLabelYUp(80, -100, 7, 5, jLtituloprincipal);
     
       ocultaBienvenida.jLabelXRight(200, 750, 3, 5, jLprose_venta);
       ocultaBienvenida.jLabelXRight(120, 750, 3, 5, jLtituloventa);
       
       ocultaBienvenida.jLabelXRight(120, 750, 3, 5, jLtituloconsulta);
      ocultaBienvenida.jLabelXRight(200, 750, 3, 5, jLconsulta_venta);
    ocultaBienvenida.jLabelXRight(200, 750, 3, 5, jLconsulta_clientes);
    ocultaBienvenida.jLabelXRight(200, 750, 3, 5, jLconsulta_productos);
   
 
    }//GEN-LAST:event_jpcatalogoMouseClicked

    private void lbbarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbbarraMousePressed

    private void lbbarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY()- y);
    }//GEN-LAST:event_lbbarraMouseDragged

    private void jPmenuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPmenuprincipalMouseClicked
        OcultaFormularios();
        
        AnimationClass muestraBienvenida = new AnimationClass();
     muestraBienvenida.jLabelYDown(-100, 80, 7, 5, jLtituloprincipal);
      
     AnimationClass ocultacatalogo = new AnimationClass();
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_clientes);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_productos);
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtitulocatalogo);
    
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLprose_venta);
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtituloventa);
    
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtituloconsulta);
      ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_venta);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_clientes);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_productos);
    

    
   
    }//GEN-LAST:event_jPmenuprincipalMouseClicked

    private void jpprocesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpprocesoMouseClicked
        OcultaFormularios();  
        
        AnimationClass muestraventa = new AnimationClass();
     muestraventa.jLabelXLeft(750, 200, 3, 5, jLprose_venta);
     muestraventa.jLabelXLeft(750, 120, 3, 5, jLtituloventa);
     
       AnimationClass ocultacatalogo = new AnimationClass();
    ocultacatalogo.jLabelYUp(80, -100, 7, 5, jLtituloprincipal);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_clientes);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_productos);
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtitulocatalogo);
      ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtituloconsulta);
      ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_venta);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_clientes);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLconsulta_productos);
    
   
    }//GEN-LAST:event_jpprocesoMouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jLcatalogo_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcatalogo_clientesMouseClicked
       IngresoCliente cli= new IngresoCliente();
        
          this.toFront();
          cli.setVisible(true);
    }//GEN-LAST:event_jLcatalogo_clientesMouseClicked

    private void jLcatalogo_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcatalogo_productosMouseClicked
        IngresoProductos ip= new IngresoProductos();
        this.toFront();
        ip.setVisible(true);
    }//GEN-LAST:event_jLcatalogo_productosMouseClicked

    private void jpconsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpconsultaMouseClicked
          OcultaFormularios();
        
        AnimationClass muestraventa = new AnimationClass();
     muestraventa.jLabelXLeft(750, 200, 3, 5, jLconsulta_venta);
     muestraventa.jLabelXLeft(750, 200, 3, 5, jLconsulta_productos);
     muestraventa.jLabelXLeft(750, 200, 3, 5, jLconsulta_clientes);
     muestraventa.jLabelXLeft(750, 120, 3, 5, jLtituloconsulta);
     
       AnimationClass ocultacatalogo = new AnimationClass();
    ocultacatalogo.jLabelYUp(80, -100, 7, 5, jLtituloprincipal);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_clientes);
    ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLcatalogo_productos);
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtitulocatalogo);
    ocultacatalogo.jLabelXRight(120, 750, 3, 5, jLtituloventa);
     ocultacatalogo.jLabelXRight(200, 750, 3, 5, jLprose_venta);
     
    
    }//GEN-LAST:event_jpconsultaMouseClicked

    private void jlconfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlconfigMouseClicked
       usuarios usu= new usuarios();
       this.toFront();
       usu.setVisible(true);
    }//GEN-LAST:event_jlconfigMouseClicked

    private void jpcerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpcerrarsesionMouseClicked
          int resp = JOptionPane.showConfirmDialog(null, "¿sEGURO DE CERRAR SESION?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 1){
             this.setVisible(true);
        }else{
         
          IngresoSistema principal= new IngresoSistema();
            principal.setVisible(true);
             this.setVisible(false);
            
        }   
    }//GEN-LAST:event_jpcerrarsesionMouseClicked

    private void jlcerrarsistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarsistemaMouseClicked
          int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de salir  ?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp == 1){
             this.setVisible(true);
        }else{
         this.dispose();
         System.exit(0);
        }
    }//GEN-LAST:event_jlcerrarsistemaMouseClicked

    private void jLconsulta_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLconsulta_ventaMouseClicked
        ConsultasVentas nueva= new  ConsultasVentas();
         this.toFront();
       nueva.setVisible(true);
    }//GEN-LAST:event_jLconsulta_ventaMouseClicked

    private void jLconsulta_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLconsulta_clientesMouseClicked
          ConsultasClientes clientes= new ConsultasClientes();
       this.toFront();
        clientes.setVisible(true);
    }//GEN-LAST:event_jLconsulta_clientesMouseClicked

    private void jLconsulta_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLconsulta_productosMouseClicked
         ConsultasProductos productos= new ConsultasProductos();
       this.toFront();
        productos.setVisible(true);
    }//GEN-LAST:event_jLconsulta_productosMouseClicked

    private void jLprose_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLprose_ventaMouseClicked
       Venta venta = new Venta();
   this.toFront();
    venta.setVisible(true);
    }//GEN-LAST:event_jLprose_ventaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btmenuflot;
    public static javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLcatalogo_clientes;
    private javax.swing.JLabel jLcatalogo_productos;
    private javax.swing.JLabel jLconsulta_clientes;
    private javax.swing.JLabel jLconsulta_productos;
    private javax.swing.JLabel jLconsulta_venta;
    private javax.swing.JLabel jLprose_venta;
    private javax.swing.JLabel jLtitulocatalogo;
    private javax.swing.JLabel jLtituloconsulta;
    private javax.swing.JLabel jLtituloprincipal;
    private javax.swing.JLabel jLtituloventa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPmenuprincipal;
    private javax.swing.JLabel jlcerrarsistema;
    private javax.swing.JLabel jlclave;
    private javax.swing.JLabel jlconfig;
    private javax.swing.JPanel jpcatalogo;
    private javax.swing.JPanel jpcerrarsesion;
    private javax.swing.JPanel jpconsulta;
    private javax.swing.JPanel jpproceso;
    private javax.swing.JPanel jpreporte;
    private javax.swing.JLabel labhora;
    private javax.swing.JLabel lbbarra;
    public static javax.swing.JLabel lblusu;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel txtfecha;
    // End of variables declaration//GEN-END:variables
}
